# Generated by Django 3.1.7 on 2021-03-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dergi',
            fields=[
                ('ISSN', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='ISSN No')),
                ('dergiAdi', models.CharField(max_length=120)),
                ('citeScore', models.CharField(max_length=120)),
                ('SNIP', models.CharField(max_length=120)),
                ('SJR', models.CharField(max_length=120)),
                ('img_src', models.CharField(max_length=200)),
                ('aimNscope', models.TextField()),
                ('last_year', models.CharField(max_length=4)),
                ('first_score', models.CharField(max_length=10)),
                ('final_score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.TextField()),
                ('PublicationNumber', models.TextField()),
                ('ISSN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dergi.dergi')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
                ('ISSN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dergi.dergi')),
            ],
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Editor', models.TextField()),
                ('EditorInfo', models.TextField()),
                ('ISSN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dergi.dergi')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesInPress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleNumber', models.CharField(max_length=100)),
                ('ISSN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dergi.dergi')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractnIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField()),
                ('ISSN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dergi.dergi')),
            ],
        ),
    ]
